version: "2"
run:
  go: "1.25"
linters:
  default: all
  enable:
    - wsl_v5
  disable:
    - bodyclose
    - cyclop
    - depguard
    - dupl
    - embeddedstructfieldcheck
    - exhaustive
    - exhaustruct
    - forbidigo
    - funlen
    - gochecknoglobals
    - gocognit
    - goconst
    - gocyclo
    - ireturn
    - lll
    - maintidx
    - nestif
    - noinlineerr
    - nonamedreturns
    - tagliatelle
    - varnamelen
    - wrapcheck
    - wsl
    - zerologlint
  settings:
    errorlint:
      asserts: false
    gocritic:
      disabled-checks:
        - unnamedResult
        - exitAfterDefer
      enabled-tags:
        - diagnostic
        - style
        - performance
        - experimental
    gosec:
      excludes:
        - G404
        - G704
      severity: high
      confidence: high
    govet:
      disable:
        - shadow
        - fieldalignment
      enable-all: true
    nakedret:
      max-func-lines: 0
    perfsprint:
      strconcat: false
    revive:
      enable-all-rules: true
      rules:
        - name: var-naming
          disabled: true
        - name: line-length-limit
          disabled: true
        - name: comment-spacings
          disabled: true
        - name: package-comments
          disabled: true
        - name: exported
          disabled: true
        - name: struct-tag
          arguments:
            - json,inline
        - name: add-constant
          disabled: true
        - name: cognitive-complexity
          disabled: true
        - name: max-public-structs
          disabled: true
        - name: function-length
          disabled: true
        - name: cyclomatic
          disabled: true
        - name: confusing-results
          disabled: true
        - name: function-result-limit
          disabled: true
        - name: flag-parameter
          disabled: true
        - name: nested-structs
          disabled: true
    sloglint:
      static-msg: true
      key-naming-case: snake
    testifylint:
      enable-all: true
    unused:
      local-variables-are-used: false
output:
  show-stats: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofmt:
      rewrite-rules:
        - pattern: interface{}
          replacement: any
        - pattern: a[b:len(a)]
          replacement: a[b:]
        - pattern: a[0:b]
          replacement: a[:b]
    gofumpt:
      extra-rules: true
